### ISSUE TITLE
dependency-free?

### ISSUE THREAD

**Issue by justin-hackin** [mikbry/material-ui-color#92]
**Is your feature request related to a problem? Please describe.**
I'm confused about why you say this is a dependency-free library when later you state one needs to have certain libraries installed.  

**Describe the solution you'd like**
Perhaps an explanation as to why these dependencies are not in your package.json dependencies for this project. 

**Describe alternatives you've considered**
N/A

I was using react-color and it wasn't doing what I wanted so I was very happy to find this.  Thank you for sharing :)

**Comment by mikbry** [comment]
Understand will clarify this.

**Comment by Gustl22** [comment]
I also think it bothers the developers more than lib size, if you have to install the dependencies by yourself and have to manually update them, if this plugin progresses with newer versions. Why not using normal dependencies in package.json ?
Thank you :)

**Comment by mikbry** [comment]
Actual peerDependencies are:
- @material-ui/core
- material-ui-popup-state
- prop-types
- react
- react-dom
- styled-components

material-ui-color is a React component based on material-ui. So if you want to use it, you need at least React and material-ui dependencies in your project. I plan to remove styled-components extra dependency.
Do you need a component without material-ui ? without React ?

**Comment by Gustl22** [comment]
@mikbry you're right, wasn't aware that [material-ui-popup-state](https://github.com/jcoreio/material-ui-popup-state) as third party lib is also shipped with MUI. That only leaves us with styled-components. Sorry that was my fault.

I also would help out there in order to remove the styled-components lib, but right now I'm quite busy.
If not already assigned, I may take a look at https://github.com/mikbry/material-ui-color/issues/56. in one or two weeks.
Best regards.

**Comment by mikbry** [comment]
Thanks @Gustl22
