### ISSUE TITLE
ColorPicker onChange event not emitted.

### ISSUE THREAD

**Issue by goldingdamien** [mikbry/material-ui-color#94]
ColorPicker is not emitting onChange event.
I am using the code below. I am using similar code for other inputs which output a console log from handleStateChange, but nothing happens with the code below.
`<ColorPicker value={state.strokeColor} defaultValue="#000" disableAlpha onChange={value => handleStateChange('strokeColor', value)} />`

Environment: Latest Chrome on Windows 10.

**Comment by Treborium** [comment]
Have the same issue with Chrome on MacOS 10.15.7. However, `onOpen` does work as expected.

I also get the following console error:

```
index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
```

**Comment by mikbry** [comment]
Thanks, I investigate this.

**Comment by maurochiozzi** [comment]
@mikbry I'm also having the same issue. The component is also performing really bad, with a high response time on change when compared with the Storybook example: if I pick one colour in the Storybook example and with the mouse button pressed I randomly move my pointer to keep picking a colour, I can see on the example the hex code changing smoothly, but I can't achieve the same performance with the same code on my environment.

And despite seeing the hex code slowly changing on my environment, the colour itself in the box doesn't change.

My console log tells me the same error as reported by @Treborium .

Env: Latest Chrome on Windows 10, React 17.0.1 embedded on Electron 10.1.5

**Comment by maurochiozzi** [comment]
@Treborium looks like this is a console warning due to an issue related between the React 16.8^ and Material-UI 4.9 (some ref [here](https://medium.com/trabe/getting-rid-of-finddomnode-method-in-your-react-application-a0d7093b2660) and [here](https://stackoverflow.com/questions/61220424/material-ui-drawer-finddomnode-is-deprecated-in-strictmode)). I got rid of this warning by removing the Fade component inside the Material-UI's Modal.

I'll be looking forward to see if this change impacts on ColorPicker performance.

**Comment by tyreepace** [comment]
Hi - was wondering if there was an update on the status of this issue? I'm running into the same problem. Thanks!

**Comment by maurochiozzi** [comment]
I gave it another shot. However, despite the lack of performance, I went back to the basics with the controlled component just as implemented on [ColorPicker](https://github.com/mikbry/material-ui-color/blob/master/stories/ColorPicker.stories.js):

`<ColorPicker value={color} onChange={handleColorChange} />`

But again, couldn't get it to work. I'll be looking for another solution since we don't have any news from this issue for like a half month. If anyone has good news for this issue, maybe I'll come back here.

**Comment by ustincameron** [comment]
Same issue with `0.4.6`, never returns an `onChange`. Surprised additional props aren't passed down.

**Comment by mikbry** [comment]
Sorry for the lack of infos, I was too busy on other projects. I will fix it by the end of this week.

**Comment by antoniogiordano** [comment]
Same issue here :-(

**Comment by willenglishiv** [comment]
yep same issue here.

**Comment by rad-eric** [comment]
same

**Comment by mikbry** [comment]
Made some tests, and I didn't replicate the bug:
https://codesandbox.io/s/material-ui-color-picker-qvcg3?file=/src/App.tsx
If you set  defaultValue, ColorPicker component became controlled and doesn't throw onChange.
Could someone with such problem do a sample in codesandbox, thanks.
I work this WE on the new version.

**Comment by mikbry** [comment]
Another example using only javascript:
https://codesandbox.io/s/material-ui-color-qb4vm?file=/src/App.js

**Comment by mikbry** [comment]
A new version v0.4.8 with a different (un)controlled management is available

**Comment by goldingdamien** [comment]
I can confirm that update value is now coming through when using defaultValue and onChange.
Thanks.

**Comment by azakero** [comment]
Still throws that error.  This is what my code looks like:

```
<ColorPicker
           className={styles.colorPicker}
           hideTextfield
           defaultValue={fillColor}
           onChange={handleFillColor}
 />
```

Any solution?
